<a href="https://colab.research.google.com/github/PravalikaM21/python_course_work/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#1D array
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#2D array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#3D array
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[3,4,6,7],[8,7,6,5]]])
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[3 4 6 7]
  [8 7 6 5]]]


In [ ]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.eye(5) # Identity matrix
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr=np.full((3,5),6)
print(arr)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [ ]:
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [ ]:
arr=np.arange(1,15,5)
print(arr)

[ 1  6 11]


In [ ]:
arr=np.linspace(1,100,5)
print(arr)

[  1.    25.75  50.5   75.25 100.  ]
